server:
  port: 8080

spring:
  application:
    name: jpa-master

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      #url: jdbc:h2:mem:test-jpa-master  # in-memory db 설정
      username: sa
      password:
      jdbc-url: jdbc:h2:~/test;AUTO_SERVER=true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
