spring:
  # h2 DB ?? - ???? ??
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  # jpa query console? ???? ??
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
