server:
  port: 8080

spring:
  application:
    name: jpa-master

  # h2 DB ?? - ???? ??
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test-jpa-master  # in-memory db 설정
    url: jdbc:h2:~/test
    username: sa
    password:

  # jpa query console? ???? ??
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
